name: Publish Plugin on Tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract GitRef (version tag)
        run: echo "GIT_REF=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Call API to create a build
        run: |
          curl -v -X POST "https://plugin-builder.btcpayserver.org/plugins/${{ env.pluginSlug }}/builds" \
          -H "Content-Type: application/json" \
          -H "Authorization: Basic $(echo -n '${{ secrets.API_USERNAME }}:${{ secrets.API_PASSWORD }}' | base64)" \
          -d '{
            "GitRef": "${{ env.GIT_REF }}"
          }'
        env:
          pluginSlug: "tronusdt" 
